# Generated by Django 4.1.4 on 2022-12-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonials',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
